version: '3.8'

services:
  visitor-counter:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped 